package ch.so.agi.mcp.change;

public enum IliModelChangeStatus {
  APPLIED,
  NO_CHANGE,
  BEFORE_MODEL_INVALID,
  AFTER_MODEL_INVALID,
  UNSUPPORTED_OPERATION,
  TARGET_NOT_FOUND,
  WRONG_TARGET_KIND,
  TARGET_IS_IMPORTED,
  NAME_ALREADY_EXISTS,
  UNEXPECTED_SEMANTIC_CHANGE
}
